const users = [
  {
    _id: "61e158abdd9a31cb75dfbb8b",
    index: 0,
    guid: "9d0fedf2-1822-43ab-a5eb-7bf393306dc3",
    isActive: false,
    balance: "$3,925.32",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Wells Witt",
    gender: "male",
    company: "EARTHMARK",
    email: "wellswitt@earthmark.com",
    phone: "+1 (866) 497-3172",
    address: "635 Putnam Avenue, Norvelt, Federated States Of Micronesia, 5711",
    about:
      "Et pariatur laborum do deserunt. Qui ut veniam cillum deserunt ut sunt ea enim. Officia dolore velit laboris in eu excepteur ipsum nisi tempor. Lorem dolore ut reprehenderit velit quis duis amet magna sit aliqua. Nostrud esse laborum cillum adipisicing proident in est cupidatat commodo quis minim. Sint deserunt in occaecat est ex duis ad amet quis consectetur ullamco. Sit Lorem adipisicing magna anim aliquip minim voluptate cupidatat nulla.\r\n",
    registered: "2016-11-10T04:13:47 +02:00",
    latitude: -88.307981,
    longitude: -39.123807,
    tags: [
      "consequat",
      "deserunt",
      "consequat",
      "non",
      "Lorem",
      "id",
      "mollit",
    ],
    friends: [
      {
        id: 0,
        name: "Kelli Elliott",
      },
      {
        id: 1,
        name: "Bradshaw Oneill",
      },
      {
        id: 2,
        name: "Marsh Pennington",
      },
    ],
    greeting: "Hello, Wells Witt! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "61e158ab73678d16793b92c3",
    index: 1,
    guid: "9f2a0f16-b7ca-4171-aaac-cbffc3531833",
    isActive: false,
    balance: "$3,445.25",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "green",
    name: "Cobb Boyle",
    gender: "male",
    company: "VIASIA",
    email: "cobbboyle@viasia.com",
    phone: "+1 (840) 536-3798",
    address: "518 Hubbard Place, Bend, South Carolina, 9179",
    about:
      "Proident dolore in occaecat culpa. Labore culpa eu ullamco fugiat nulla ipsum irure consectetur ut elit officia eiusmod. Consequat non do aliquip id eiusmod laborum consectetur sit anim ullamco consectetur quis ad officia. Do nisi proident incididunt cillum in id sit eu ipsum. Do exercitation anim adipisicing nisi aliquip cillum fugiat.\r\n",
    registered: "2014-08-04T06:42:00 +03:00",
    latitude: -33.53926,
    longitude: -147.686836,
    tags: [
      "consequat",
      "culpa",
      "est",
      "reprehenderit",
      "ad",
      "elit",
      "dolore",
    ],
    friends: [
      {
        id: 0,
        name: "Schultz Walsh",
      },
      {
        id: 1,
        name: "Knowles Alexander",
      },
      {
        id: 2,
        name: "Sears Moore",
      },
    ],
    greeting: "Hello, Cobb Boyle! You have 4 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "61e158abe23c808c2ac5c104",
    index: 2,
    guid: "be67111c-24b5-4cff-81b0-efcc3af5b36a",
    isActive: true,
    balance: "$1,641.07",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Dianna Sharp",
    gender: "female",
    company: "SIGNIDYNE",
    email: "diannasharp@signidyne.com",
    phone: "+1 (902) 458-2390",
    address: "594 Otsego Street, Coaldale, Vermont, 5852",
    about:
      "Anim cillum enim anim laborum cillum labore in ipsum officia aute nostrud officia. Dolor aliquip pariatur dolore occaecat magna nostrud non et. Voluptate labore elit tempor elit veniam dolore irure.\r\n",
    registered: "2016-08-27T02:23:49 +03:00",
    latitude: -12.854569,
    longitude: 177.242466,
    tags: ["do", "esse", "amet", "ipsum", "velit", "ex", "eiusmod"],
    friends: [
      {
        id: 0,
        name: "Sutton Gallegos",
      },
      {
        id: 1,
        name: "Hester Abbott",
      },
      {
        id: 2,
        name: "Steele Sears",
      },
    ],
    greeting: "Hello, Dianna Sharp! You have 5 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "61e158ab5b07496980bfc491",
    index: 3,
    guid: "39e59842-fd4d-4382-af50-ee665d0e0c2f",
    isActive: true,
    balance: "$1,735.46",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "blue",
    name: "Campos Odonnell",
    gender: "male",
    company: "AQUASURE",
    email: "camposodonnell@aquasure.com",
    phone: "+1 (983) 450-3988",
    address: "839 Navy Walk, Emerald, Alaska, 579",
    about:
      "Duis ut qui ut occaecat consectetur aliquip nostrud velit proident dolor ea commodo irure. Id occaecat sint duis velit sit laborum veniam fugiat voluptate proident incididunt elit voluptate ea. Eu sunt mollit proident ad sit do consectetur duis anim adipisicing tempor incididunt commodo eiusmod. Ipsum magna cupidatat occaecat reprehenderit qui nisi ea in et consectetur sit nisi. Ad duis est occaecat aliquip aute est. Culpa minim quis eu amet proident ad.\r\n",
    registered: "2016-10-21T11:16:31 +02:00",
    latitude: 28.792011,
    longitude: -170.783976,
    tags: [
      "occaecat",
      "voluptate",
      "in",
      "est",
      "sint",
      "voluptate",
      "voluptate",
    ],
    friends: [
      {
        id: 0,
        name: "Stafford Cobb",
      },
      {
        id: 1,
        name: "Gregory Hopkins",
      },
      {
        id: 2,
        name: "Henderson Allen",
      },
    ],
    greeting: "Hello, Campos Odonnell! You have 2 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "61e158aba3c896de2b09736c",
    index: 4,
    guid: "4d1deeac-e9fe-4cb9-8d07-e47b6cdad7a5",
    isActive: true,
    balance: "$2,004.59",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "brown",
    name: "Delia Simon",
    gender: "female",
    company: "GALLAXIA",
    email: "deliasimon@gallaxia.com",
    phone: "+1 (958) 591-3427",
    address: "999 Moore Street, Driftwood, North Dakota, 6250",
    about:
      "Cillum enim deserunt veniam esse qui exercitation officia occaecat. Ex ad id irure exercitation anim voluptate sit elit cupidatat fugiat officia. Dolor tempor proident adipisicing exercitation sint duis ad adipisicing. Ad anim elit et sit aliqua ipsum incididunt Lorem nulla nisi do.\r\n",
    registered: "2016-05-07T07:08:07 +03:00",
    latitude: -2.178189,
    longitude: 35.390811,
    tags: ["ut", "magna", "ad", "incididunt", "aliquip", "amet", "dolor"],
    friends: [
      {
        id: 0,
        name: "Jefferson Whitehead",
      },
      {
        id: 1,
        name: "Ingrid Doyle",
      },
      {
        id: 2,
        name: "Greer Glover",
      },
    ],
    greeting: "Hello, Delia Simon! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "61e158ab37ab85a8e132cc1c",
    index: 5,
    guid: "1db7d6ab-1bb8-445f-9351-1f7a0a34e9af",
    isActive: false,
    balance: "$1,228.63",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "brown",
    name: "Puckett Richmond",
    gender: "male",
    company: "FITCORE",
    email: "puckettrichmond@fitcore.com",
    phone: "+1 (903) 525-2670",
    address: "941 Varick Avenue, Dunbar, Iowa, 6531",
    about:
      "Adipisicing esse aute eiusmod duis laboris voluptate id deserunt officia cillum occaecat cillum. Excepteur ea ea nostrud incididunt reprehenderit aute amet est. Commodo adipisicing aliqua consequat nulla adipisicing. Eiusmod enim reprehenderit proident enim esse. Fugiat ut cupidatat et nostrud qui cillum consequat tempor proident laborum. Qui ex id enim incididunt non occaecat velit elit. Ad quis fugiat sunt officia culpa ut eiusmod.\r\n",
    registered: "2019-02-04T12:16:37 +02:00",
    latitude: 34.704273,
    longitude: -46.611759,
    tags: ["nisi", "ad", "ut", "veniam", "ut", "mollit", "excepteur"],
    friends: [
      {
        id: 0,
        name: "Josefa Mathis",
      },
      {
        id: 1,
        name: "Martina Mendoza",
      },
      {
        id: 2,
        name: "Barron Petty",
      },
    ],
    greeting: "Hello, Puckett Richmond! You have 6 unread messages.",
    favoriteFruit: "apple",
  },
];

module.exports = users;
